app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

app_contact:
    resource: "@AppBundle/Resources/config/routing/contact.yml"
    prefix:   /contact