AppBundle\Entity\User:
    type:  entity
    table: fos_user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO

    manyToOne:
        contacts:
            targetEntity: Contact
            mappedBy: user
            cascade: [ persist ]
            joinColumn:
                onDelete: cascade